plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/tiequwangmonolith/Desktop/游戏资料/游戏项目/huanzi-lipstick-demo"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]